
# This file has been generated at Fri Dec  7 17:00:56 2018

from openalea.core import *


__name__ = 'EnergyBalance'

__editable__ = True
__description__ = 'CropML Model library.'
__license__ = 'CECILL-C'
__url__ = 'http://pycropml.rtfd.org'
__alias__ = []
__version__ = '0.0.1'
__authors__ = 'OpenAlea Consortium'
__institutes__ = 'INRA/CIRAD'
__icon__ = ''


__all__ = ['evapotranspiration_evapotranspiration', 'diffusionlimitedevaporation_diffusionlimitedevaporation', 'netradiation_netradiation', 'soilevaporation_soilevaporation', '_88001280', 'priestlytaylor_priestlytaylor', 'penman_penman', 'potentialtranspiration_potentialtranspiration', 'ptsoil_ptsoil', 'canopytemperature_canopytemperature', 'conductance_conductance', 'cropheatflux_cropheatflux', 'soilheatflux_soilheatflux', 'netradiationequivalentevaporation_netradiationequivalentevaporation']



evapotranspiration_evapotranspiration = Factory(name='EvapoTranspiration',
                authors='OpenAlea Consortium (wralea authors)',
                description='According to the availability of wind and/or vapor pressure daily data, the\n            SiriusQuality2 model calculates the evapotranspiration rate using the Penman (if wind\n            and vapor pressure data are available) (Penman 1948) or the Priestly-Taylor\n            (Priestley and Taylor 1972) method ',
                category='Unclassified',
                nodemodule='evapotranspiration',
                nodeclass='evapotranspiration',
                inputs=[{'interface': IInt(min=0, max=1, step=1), 'name': 'isWindVpDefined', 'value': 1}, {'interface': IFloat(min=0, max=10000, step=1.000000), 'name': 'evapoTranspirationPriestlyTaylor', 'value': 449.367}, {'interface': IFloat(min=0, max=10000, step=1.000000), 'name': 'evapoTranspirationPenman', 'value': 830.958}],
                outputs=[{'interface': IFloat(min=0, max=10000, step=1.000000), 'name': 'evapoTranspiration'}],
                widgetmodule=None,
                widgetclass=None,
               )




diffusionlimitedevaporation_diffusionlimitedevaporation = Factory(name='DiffusionLimitedEvaporation',
                authors='OpenAlea Consortium (wralea authors)',
                description='the evaporation from the diffusion limited soil ',
                category='Unclassified',
                nodemodule='diffusionlimitedevaporation',
                nodeclass='diffusionlimitedevaporation',
                inputs=[{'interface': IFloat(min=0, max=10000, step=1.000000), 'name': 'deficitOnTopLayers', 'value': 5341}, {'interface': IFloat(min=0, max=10, step=1.000000), 'name': 'soilDiffusionConstant', 'value': 4.2}],
                outputs=[{'interface': IFloat(min=0, max=5000, step=1.000000), 'name': 'diffusionLimitedEvaporation'}],
                widgetmodule=None,
                widgetclass=None,
               )




netradiation_netradiation = Factory(name='NetRadiation',
                authors='OpenAlea Consortium (wralea authors)',
                description='It is calculated at the surface of the canopy and is givenby the difference between incoming and outgoing radiation of both short \n                     and long wavelength radiation ',
                category='Unclassified',
                nodemodule='netradiation',
                nodeclass='netradiation',
                inputs=[{'interface': IFloat(min=-30, max=45, step=1.000000), 'name': 'minTair', 'value': 0.7}, {'interface': IFloat(min=-30, max=45, step=1.000000), 'name': 'maxTair', 'value': 7.2}, {'interface': IFloat(min=0, max=1, step=1.000000), 'name': 'albedoCoefficient', 'value': 0.23}, {'interface': IFloat(min=0, max=1, step=1.000000), 'name': 'stefanBoltzman', 'value': 4.903e-09}, {'interface': IFloat(min=-500, max=10000, step=1.000000), 'name': 'elevation', 'value': 0}, {'interface': IFloat(min=0, max=1000, step=1.000000), 'name': 'solarRadiation', 'value': 3}, {'interface': IFloat(min=0, max=1000, step=1.000000), 'name': 'vaporPressure', 'value': 6.1}, {'interface': IFloat(min=0, max=1000, step=1.000000), 'name': 'extraSolarRadiation', 'value': 11.7}],
                outputs=[{'interface': IFloat(min=0, max=5000, step=1.000000), 'name': 'netRadiation'}, {'interface': IFloat(min=0, max=5000, step=1.000000), 'name': 'netOutGoingLongWaveRadiation'}],
                widgetmodule=None,
                widgetclass=None,
               )




soilevaporation_soilevaporation = Factory(name='SoilEvaporation',
                authors='OpenAlea Consortium (wralea authors)',
                description='Starting from a soil at field capacity, soil evaporation  is assumed to\n                be energy limited during the first phase of evaporation and diffusion limited thereafter.\n                Hence, the soil evaporation model considers these two processes taking the minimum between\n                the energy limited evaporation (PtSoil) and the diffused limited\n                evaporation ',
                category='Unclassified',
                nodemodule='soilevaporation',
                nodeclass='soilevaporation',
                inputs=[{'interface': IFloat(min=0, max=10000, step=1.000000), 'name': 'diffusionLimitedEvaporation', 'value': 6605.505}, {'interface': IFloat(min=0, max=1000, step=1.000000), 'name': 'energyLimitedEvaporation', 'value': 448.24}],
                outputs=[{'interface': IFloat(min=0, max=5000, step=1.000000), 'name': 'soilEvaporation'}],
                widgetmodule=None,
                widgetclass=None,
               )




_88001280 = CompositeNodeFactory(name='EnergyBalance_wf',
                             description='',
                             category='',
                             doc='\n\n\n    EnergyBalance\n    Author: Pierre MARTRE\n    Reference: Modelling energy balance in the wheat crop model SiriusQuality2: Evapotranspiration and canopy and soil temperature calculations\n    Institution: INRA/LEPSE\n    Abstract: see documentation at http://www1.clermont.inra.fr/siriusquality/?page_id=547\n',
                             inputs=[  {  'interface': IFloat(min=-30, max=45, step=1.000000),
      'name': 'minTair',
      'value': 0.7},
   {  'interface': IFloat(min=-30, max=45, step=1.000000),
      'name': 'maxTair',
      'value': 7.2},
   {  'interface': IFloat(min=0, max=1, step=1.000000),
      'name': 'albedoCoefficient',
      'value': 0.23},
   {  'interface': IFloat(min=0, max=1, step=1.000000),
      'name': 'stefanBoltzman',
      'value': 4.903e-09},
   {  'interface': IFloat(min=-500, max=10000, step=1.000000),
      'name': 'elevation'},
   {  'interface': IFloat(min=0, max=1000, step=1.000000),
      'name': 'solarRadiation',
      'value': 3},
   {  'interface': IFloat(min=0, max=1000, step=1.000000),
      'name': 'vaporPressure',
      'value': 6.1},
   {  'interface': IFloat(min=0, max=1000, step=1.000000),
      'name': 'extraSolarRadiation',
      'value': 11.7},
   {  'interface': IFloat(min=0, max=10, step=1.000000),
      'name': 'lambdaV',
      'value': 2.454},
   {  'interface': IFloat(min=0, max=1000, step=1.000000),
      'name': 'hslope',
      'value': 0.584},
   {  'interface': IFloat(min=0, max=1, step=1.000000),
      'name': 'psychrometricConstant',
      'value': 0.66},
   {  'interface': IFloat(min=0, max=100, step=1.000000),
      'name': 'Alpha',
      'value': 1.5},
   {  'interface': IFloat(min=0, max=1, step=1.000000),
      'name': 'vonKarman',
      'value': 0.42},
   {  'interface': IFloat(min=0, max=10, step=1.000000),
      'name': 'heightWeatherMeasurements',
      'value': 2},
   {  'interface': IFloat(min=0, max=1, step=1.000000),
      'name': 'zm',
      'value': 0.13},
   {  'interface': IFloat(min=0, max=1, step=1.000000),
      'name': 'd',
      'value': 0.67},
   {  'interface': IFloat(min=0, max=1, step=1.000000),
      'name': 'zh',
      'value': 0.013},
   {  'interface': IFloat(min=0, max=1000, step=1.000000),
      'name': 'plantHeight'},
   {  'interface': IFloat(min=0, max=1000000, step=1.000000),
      'name': 'wind',
      'value': 124000},
   {  'interface': IFloat(min=0, max=10000, step=1.000000),
      'name': 'deficitOnTopLayers',
      'value': 5341},
   {  'interface': IFloat(min=0, max=10, step=1.000000),
      'name': 'soilDiffusionConstant',
      'value': 4.2},
   {  'interface': IFloat(min=0, max=1000, step=1.000000),
      'name': 'VPDair',
      'value': 2.19},
   {  'interface': IFloat, 'name': 'rhoDensityAir', 'value': 1.225},
   {  'interface': IFloat(min=0, max=1, step=1.000000),
      'name': 'specificHeatCapacityAir',
      'value': 0.00101},
   {  'interface': IFloat(min=0, max=100, step=1.000000),
      'name': 'tau',
      'value': 0.9983},
   {  'interface': IFloat(min=0, max=1, step=1.000000),
      'name': 'tauAlpha',
      'value': 0.3},
   {  'interface': IInt(min=0, max=1, step=1),
      'name': 'isWindVpDefined',
      'value': 1}],
                             outputs=[  {  'interface': IFloat(min=0, max=5000, step=1.000000),
      'name': 'netRadiation'},
   {  'interface': IFloat(min=0, max=5000, step=1.000000),
      'name': 'netOutGoingLongWaveRadiation'},
   {  'interface': IFloat(min=0, max=5000, step=1.000000),
      'name': 'netRadiationEquivalentEvaporation'},
   {  'interface': IFloat(min=0, max=10000, step=1.000000),
      'name': 'evapoTranspirationPriestlyTaylor'},
   {  'interface': IFloat(min=0, max=5000, step=1.000000),
      'name': 'diffusionLimitedEvaporation'},
   {  'interface': IFloat(min=0, max=5000, step=1.000000),
      'name': 'energyLimitedEvaporation'},
   {  'interface': IFloat(min=0, max=10000, step=1.000000),
      'name': 'conductance'},
   {  'interface': IFloat(min=0, max=5000, step=1.000000),
      'name': 'evapoTranspirationPenman'},
   {  'interface': IFloat(min=0, max=5000, step=1.000000),
      'name': 'soilEvaporation'},
   {  'interface': IFloat(min=0, max=10000, step=1.000000),
      'name': 'evapoTranspiration'},
   {  'interface': IFloat(min=0, max=10000, step=1.000000),
      'name': 'potentialTranspiration'},
   {  'interface': IFloat(min=0, max=10000, step=1.000000),
      'name': 'soilHeatFlux'},
   {  'interface': IFloat(min=0, max=10000, step=1.000000),
      'name': 'cropHeatFlux'},
   {  'interface': IFloat(min=-30, max=45, step=1.000000),
      'name': 'minCanopyTemperature'},
   {  'interface': IFloat(min=-30, max=45, step=1.000000),
      'name': 'maxCanopyTemperature'}],
                             elt_factory={  2: ('EnergyBalance', 'NetRadiation'),
   3: ('EnergyBalance', 'NetRadiationEquivalentEvaporation'),
   4: ('EnergyBalance', 'PriestlyTaylor'),
   5: ('EnergyBalance', 'Conductance'),
   6: ('EnergyBalance', 'DiffusionLimitedEvaporation'),
   7: ('EnergyBalance', 'Penman'),
   8: ('EnergyBalance', 'PtSoil'),
   9: ('EnergyBalance', 'SoilEvaporation'),
   10: ('EnergyBalance', 'EvapoTranspiration'),
   11: ('EnergyBalance', 'SoilHeatFlux'),
   12: ('EnergyBalance', 'PotentialTranspiration'),
   13: ('EnergyBalance', 'CropHeatFlux'),
   14: ('EnergyBalance', 'CanopyTemperature')},
                             elt_connections={  40923656L: ('__in__', 20, 6, 1),
   40923680L: ('__in__', 19, 6, 0),
   40923704L: ('__in__', 18, 5, 6),
   40923728L: ('__in__', 17, 5, 5),
   40923752L: ('__in__', 16, 5, 3),
   40923776L: ('__in__', 15, 5, 4),
   40923800L: ('__in__', 14, 5, 2),
   40923824L: ('__in__', 13, 5, 1),
   40923848L: ('__in__', 12, 5, 0),
   40923872L: ('__in__', 11, 4, 3),
   40923896L: ('__in__', 10, 4, 2),
   40923920L: ('__in__', 9, 4, 1),
   40923944L: ('__in__', 8, 3, 0),
   40923968L: ('__in__', 7, 2, 7),
   40923992L: ('__in__', 6, 2, 6),
   40924016L: ('__in__', 5, 2, 5),
   40924040L: ('__in__', 4, 2, 4),
   40924064L: ('__in__', 3, 2, 3),
   40924088L: ('__in__', 2, 2, 2),
   40924112L: ('__in__', 1, 2, 1),
   40924136L: ('__in__', 0, 2, 0),
   40924160L: (14, 1, '__out__', 14),
   40924184L: (14, 0, '__out__', 13),
   40924208L: (13, 0, '__out__', 12),
   40924232L: (11, 0, '__out__', 11),
   40924256L: (12, 0, '__out__', 10),
   40924280L: (10, 0, '__out__', 9),
   40924304L: (9, 0, '__out__', 8),
   40924328L: (7, 0, '__out__', 7),
   40924352L: (5, 0, '__out__', 6),
   40924376L: (8, 0, '__out__', 5),
   40924400L: (6, 0, '__out__', 4),
   40924424L: (4, 0, '__out__', 3),
   40924448L: (3, 0, '__out__', 2),
   40924472L: (2, 1, '__out__', 1),
   40924496L: (2, 0, '__out__', 0),
   40924808L: (13, 0, 14, 2),
   40924832L: (11, 0, 13, 1),
   40924856L: (12, 0, 13, 2),
   40924880L: (10, 0, 12, 0),
   40924904L: (9, 0, 11, 2),
   40924928L: (7, 0, 10, 2),
   40924952L: (5, 0, 14, 3),
   40924976L: (5, 0, 7, 8),
   40925000L: (8, 0, 9, 1),
   40925024L: (6, 0, 9, 0),
   40925048L: (4, 0, 10, 1),
   40925072L: (4, 0, 7, 0),
   40925096L: (4, 0, 8, 0),
   40925120L: (3, 0, 13, 0),
   40925144L: (3, 0, 11, 0),
   40925168L: (3, 0, 4, 0),
   40925192L: (2, 0, 3, 1),
   40925216L: ('__in__', 23, 14, 6),
   40925240L: ('__in__', 22, 14, 5),
   40925264L: ('__in__', 8, 14, 4),
   40925288L: ('__in__', 1, 14, 1),
   40925312L: ('__in__', 0, 14, 0),
   40925336L: ('__in__', 24, 12, 1),
   40925360L: ('__in__', 24, 11, 1),
   40925384L: ('__in__', 26, 10, 0),
   40925408L: ('__in__', 25, 8, 3),
   40925432L: ('__in__', 24, 8, 2),
   40925456L: ('__in__', 11, 8, 1),
   40925480L: ('__in__', 23, 7, 7),
   40925504L: ('__in__', 22, 7, 6),
   40925528L: ('__in__', 8, 7, 5),
   40925552L: ('__in__', 11, 7, 4),
   40925576L: ('__in__', 10, 7, 3),
   40925600L: ('__in__', 21, 7, 2),
   40925624L: ('__in__', 9, 7, 1)},
                             elt_data={  2: {  'block': False,
         'caption': 'NetRadiation',
         'delay': 0,
         'hide': True,
         'id': 2,
         'lazy': True,
         'port_hide_changed': set([]),
         'posx': 0,
         'posy': 0,
         'priority': 0,
         'use_user_color': True,
         'user_application': None,
         'user_color': None},
   3: {  'block': False,
         'caption': 'NetRadiationEquivalentEvaporation',
         'delay': 0,
         'hide': True,
         'id': 3,
         'lazy': True,
         'port_hide_changed': set([]),
         'posx': 0,
         'posy': 0,
         'priority': 0,
         'use_user_color': True,
         'user_application': None,
         'user_color': None},
   4: {  'block': False,
         'caption': 'PriestlyTaylor',
         'delay': 0,
         'hide': True,
         'id': 4,
         'lazy': True,
         'port_hide_changed': set([]),
         'posx': 0,
         'posy': 0,
         'priority': 0,
         'use_user_color': True,
         'user_application': None,
         'user_color': None},
   5: {  'block': False,
         'caption': 'Conductance',
         'delay': 0,
         'hide': True,
         'id': 5,
         'lazy': True,
         'port_hide_changed': set([]),
         'posx': 0,
         'posy': 0,
         'priority': 0,
         'use_user_color': True,
         'user_application': None,
         'user_color': None},
   6: {  'block': False,
         'caption': 'DiffusionLimitedEvaporation',
         'delay': 0,
         'hide': True,
         'id': 6,
         'lazy': True,
         'port_hide_changed': set([]),
         'posx': 0,
         'posy': 0,
         'priority': 0,
         'use_user_color': True,
         'user_application': None,
         'user_color': None},
   7: {  'block': False,
         'caption': 'Penman',
         'delay': 0,
         'hide': True,
         'id': 7,
         'lazy': True,
         'port_hide_changed': set([]),
         'posx': 0,
         'posy': 0,
         'priority': 0,
         'use_user_color': True,
         'user_application': None,
         'user_color': None},
   8: {  'block': False,
         'caption': 'PtSoil',
         'delay': 0,
         'hide': True,
         'id': 8,
         'lazy': True,
         'port_hide_changed': set([]),
         'posx': 0,
         'posy': 0,
         'priority': 0,
         'use_user_color': True,
         'user_application': None,
         'user_color': None},
   9: {  'block': False,
         'caption': 'SoilEvaporation',
         'delay': 0,
         'hide': True,
         'id': 9,
         'lazy': True,
         'port_hide_changed': set([]),
         'posx': 0,
         'posy': 0,
         'priority': 0,
         'use_user_color': True,
         'user_application': None,
         'user_color': None},
   10: {  'block': False,
          'caption': 'EvapoTranspiration',
          'delay': 0,
          'hide': True,
          'id': 10,
          'lazy': True,
          'port_hide_changed': set([]),
          'posx': 0,
          'posy': 0,
          'priority': 0,
          'use_user_color': True,
          'user_application': None,
          'user_color': None},
   11: {  'block': False,
          'caption': 'SoilHeatFlux',
          'delay': 0,
          'hide': True,
          'id': 11,
          'lazy': True,
          'port_hide_changed': set([]),
          'posx': 0,
          'posy': 0,
          'priority': 0,
          'use_user_color': True,
          'user_application': None,
          'user_color': None},
   12: {  'block': False,
          'caption': 'PotentialTranspiration',
          'delay': 0,
          'hide': True,
          'id': 12,
          'lazy': True,
          'port_hide_changed': set([]),
          'posx': 0,
          'posy': 0,
          'priority': 0,
          'use_user_color': True,
          'user_application': None,
          'user_color': None},
   13: {  'block': False,
          'caption': 'CropHeatFlux',
          'delay': 0,
          'hide': True,
          'id': 13,
          'lazy': True,
          'port_hide_changed': set([]),
          'posx': 0,
          'posy': 0,
          'priority': 0,
          'use_user_color': True,
          'user_application': None,
          'user_color': None},
   14: {  'block': False,
          'caption': 'CanopyTemperature',
          'delay': 0,
          'hide': True,
          'id': 14,
          'lazy': True,
          'port_hide_changed': set([]),
          'posx': 0,
          'posy': 0,
          'priority': 0,
          'use_user_color': True,
          'user_application': None,
          'user_color': None},
   '__in__': {  'block': False,
                'caption': 'In',
                'delay': 0,
                'hide': True,
                'id': 0,
                'lazy': True,
                'port_hide_changed': set([]),
                'posx': 0,
                'posy': 0,
                'priority': 0,
                'use_user_color': True,
                'user_application': None,
                'user_color': None},
   '__out__': {  'block': False,
                 'caption': 'Out',
                 'delay': 0,
                 'hide': True,
                 'id': 1,
                 'lazy': True,
                 'port_hide_changed': set([]),
                 'posx': 0,
                 'posy': 0,
                 'priority': 0,
                 'use_user_color': True,
                 'user_application': None,
                 'user_color': None}},
                             elt_value={  2: [],
   3: [],
   4: [],
   5: [],
   6: [],
   7: [],
   8: [],
   9: [],
   10: [],
   11: [],
   12: [],
   13: [],
   14: [],
   '__in__': [],
   '__out__': []},
                             elt_ad_hoc={  2: {'position': [0, 0], 'userColor': None, 'useUserColor': True},
   3: {'position': [0, 0], 'userColor': None, 'useUserColor': True},
   4: {'position': [0, 0], 'userColor': None, 'useUserColor': True},
   5: {'position': [0, 0], 'userColor': None, 'useUserColor': True},
   6: {'position': [0, 0], 'userColor': None, 'useUserColor': True},
   7: {'position': [0, 0], 'userColor': None, 'useUserColor': True},
   8: {'position': [0, 0], 'userColor': None, 'useUserColor': True},
   9: {'position': [0, 0], 'userColor': None, 'useUserColor': True},
   10: {'position': [0, 0], 'userColor': None, 'useUserColor': True},
   11: {'position': [0, 0], 'userColor': None, 'useUserColor': True},
   12: {'position': [0, 0], 'userColor': None, 'useUserColor': True},
   13: {'position': [0, 0], 'userColor': None, 'useUserColor': True},
   14: {'position': [0, 0], 'userColor': None, 'useUserColor': True},
   '__in__': {'position': [0, 0], 'userColor': None, 'useUserColor': True},
   '__out__': {'position': [0, 0], 'userColor': None, 'useUserColor': True}},
                             lazy=True,
                             eval_algo=None,
                             )




priestlytaylor_priestlytaylor = Factory(name='PriestlyTaylor',
                authors='OpenAlea Consortium (wralea authors)',
                description='Calculate Energy Balance ',
                category='Unclassified',
                nodemodule='priestlytaylor',
                nodeclass='priestlytaylor',
                inputs=[{'interface': IFloat(min=0, max=5000, step=1.000000), 'name': 'netRadiationEquivalentEvaporation', 'value': 638.142}, {'interface': IFloat(min=0, max=1000, step=1.000000), 'name': 'hslope', 'value': 0.584}, {'interface': IFloat(min=0, max=1, step=1.000000), 'name': 'psychrometricConstant', 'value': 0.66}, {'interface': IFloat(min=0, max=100, step=1.000000), 'name': 'Alpha', 'value': 1.5}],
                outputs=[{'interface': IFloat(min=0, max=10000, step=1.000000), 'name': 'evapoTranspirationPriestlyTaylor'}],
                widgetmodule=None,
                widgetclass=None,
               )




penman_penman = Factory(name='Penman',
                authors='OpenAlea Consortium (wralea authors)',
                description='This method is used when wind and vapor pressure daily data are available \n        ',
                category='Unclassified',
                nodemodule='penman',
                nodeclass='penman',
                inputs=[{'interface': IFloat(min=0, max=10000, step=1.000000), 'name': 'evapoTranspirationPriestlyTaylor', 'value': 449.367}, {'interface': IFloat(min=0, max=1000, step=1.000000), 'name': 'hslope', 'value': 0.584}, {'interface': IFloat(min=0, max=1000, step=1.000000), 'name': 'VPDair', 'value': 2.19}, {'interface': IFloat(min=0, max=1, step=1.000000), 'name': 'psychrometricConstant', 'value': 0.66}, {'interface': IFloat(min=0, max=100, step=1.000000), 'name': 'Alpha', 'value': 1.5}, {'interface': IFloat(min=0, max=10, step=1.000000), 'name': 'lambdaV', 'value': 2.454}, {'interface': IFloat, 'name': 'rhoDensityAir', 'value': 1.225}, {'interface': IFloat(min=0, max=1, step=1.000000), 'name': 'specificHeatCapacityAir', 'value': 0.00101}, {'interface': IFloat(min=0, max=10000, step=1.000000), 'name': 'conductance', 'value': 598.685}],
                outputs=[{'interface': IFloat(min=0, max=5000, step=1.000000), 'name': 'evapoTranspirationPenman'}],
                widgetmodule=None,
                widgetclass=None,
               )




potentialtranspiration_potentialtranspiration = Factory(name='PotentialTranspiration',
                authors='OpenAlea Consortium (wralea authors)',
                description='SiriusQuality2 uses availability of water from the soil reservoir as a method to restrict\n                    transpiration as soil moisture is depleted ',
                category='Unclassified',
                nodemodule='potentialtranspiration',
                nodeclass='potentialtranspiration',
                inputs=[{'interface': IFloat(min=0, max=10000, step=1.000000), 'name': 'evapoTranspiration', 'value': 830.958}, {'interface': IFloat(min=0, max=1, step=1.000000), 'name': 'tau', 'value': 0.9983}],
                outputs=[{'interface': IFloat(min=0, max=10000, step=1.000000), 'name': 'potentialTranspiration'}],
                widgetmodule=None,
                widgetclass=None,
               )




ptsoil_ptsoil = Factory(name='PtSoil',
                authors='OpenAlea Consortium (wralea authors)',
                description='Evaporation from the soil in the energy-limited stage ',
                category='Unclassified',
                nodemodule='ptsoil',
                nodeclass='ptsoil',
                inputs=[{'interface': IFloat(min=0, max=1000, step=1.000000), 'name': 'evapoTranspirationPriestlyTaylor', 'value': 120}, {'interface': IFloat(min=0, max=100, step=1.000000), 'name': 'Alpha', 'value': 1.5}, {'interface': IFloat(min=0, max=100, step=1.000000), 'name': 'tau', 'value': 0.9983}, {'interface': IFloat(min=0, max=1, step=1.000000), 'name': 'tauAlpha', 'value': 0.3}],
                outputs=[{'interface': IFloat(min=0, max=5000, step=1.000000), 'name': 'energyLimitedEvaporation'}],
                widgetmodule=None,
                widgetclass=None,
               )




canopytemperature_canopytemperature = Factory(name='CanopyTemperature',
                authors='OpenAlea Consortium (wralea authors)',
                description='It is calculated from the crop heat flux and the boundary layer conductance ',
                category='Unclassified',
                nodemodule='canopytemperature',
                nodeclass='canopytemperature',
                inputs=[{'interface': IFloat(min=-30, max=45, step=1.000000), 'name': 'minTair', 'value': 0.7}, {'interface': IFloat(min=-30, max=45, step=1.000000), 'name': 'maxTair', 'value': 7.2}, {'interface': IFloat(min=0, max=10000, step=1.000000), 'name': 'cropHeatFlux', 'value': 447.912}, {'interface': IFloat(min=0, max=10000, step=1.000000), 'name': 'conductance', 'value': 598.685}, {'interface': IFloat(min=0, max=10, step=1.000000), 'name': 'lambdaV', 'value': 2.454}, {'interface': IFloat, 'name': 'rhoDensityAir', 'value': 1.225}, {'interface': IFloat, 'name': 'specificHeatCapacityAir', 'value': 0.00101}],
                outputs=[{'interface': IFloat(min=-30, max=45, step=1.000000), 'name': 'minCanopyTemperature'}, {'interface': IFloat(min=-30, max=45, step=1.000000), 'name': 'maxCanopyTemperature'}],
                widgetmodule=None,
                widgetclass=None,
               )




conductance_conductance = Factory(name='Conductance',
                authors='OpenAlea Consortium (wralea authors)',
                description='The boundary layer conductance is expressed as the wind speed profile above the\n            canopy and the canopy structure. The approach does not take into account buoyancy\n            effects. ',
                category='Unclassified',
                nodemodule='conductance',
                nodeclass='conductance',
                inputs=[{'interface': IFloat(min=0, max=1, step=1.000000), 'name': 'vonKarman', 'value': 0.42}, {'interface': IFloat(min=0, max=10, step=1.000000), 'name': 'heightWeatherMeasurements', 'value': 2}, {'interface': IFloat(min=0, max=1, step=1.000000), 'name': 'zm', 'value': 0.13}, {'interface': IFloat(min=0, max=1, step=1.000000), 'name': 'zh', 'value': 0.013}, {'interface': IFloat(min=0, max=1, step=1.000000), 'name': 'd', 'value': 0.67}, {'interface': IFloat(min=0, max=1000, step=1.000000), 'name': 'plantHeight', 'value': 0}, {'interface': IFloat(min=0, max=1000000, step=1.000000), 'name': 'wind', 'value': 124000}],
                outputs=[{'interface': IFloat(min=0, max=10000, step=1.000000), 'name': 'conductance'}],
                widgetmodule=None,
                widgetclass=None,
               )




cropheatflux_cropheatflux = Factory(name='CropHeatFlux',
                authors='OpenAlea Consortium (wralea authors)',
                description='It is calculated from net Radiation, soil heat flux and potential transpiration ',
                category='Unclassified',
                nodemodule='cropheatflux',
                nodeclass='cropheatflux',
                inputs=[{'interface': IFloat(min=0, max=10000, step=1.000000), 'name': 'netRadiationEquivalentEvaporation', 'value': 638.142}, {'interface': IFloat(min=0, max=1000, step=1.000000), 'name': 'soilHeatFlux', 'value': 188.817}, {'interface': IFloat(min=0, max=1000, step=1.000000), 'name': 'potentialTranspiration', 'value': 1.413}],
                outputs=[{'interface': IFloat(min=0, max=10000, step=1.000000), 'name': 'cropHeatFlux'}],
                widgetmodule=None,
                widgetclass=None,
               )




soilheatflux_soilheatflux = Factory(name='SoilHeatFlux',
                authors='OpenAlea Consortium (wralea authors)',
                description='The available energy in the soil ',
                category='Unclassified',
                nodemodule='soilheatflux',
                nodeclass='soilheatflux',
                inputs=[{'interface': IFloat(min=0, max=5000, step=1.000000), 'name': 'netRadiationEquivalentEvaporation', 'value': 638.142}, {'interface': IFloat(min=0, max=100, step=1.000000), 'name': 'tau', 'value': 0.9983}, {'interface': IFloat(min=0, max=10000, step=1.000000), 'name': 'soilEvaporation', 'value': 448.24}],
                outputs=[{'interface': IFloat(min=0, max=10000, step=1.000000), 'name': 'soilHeatFlux'}],
                widgetmodule=None,
                widgetclass=None,
               )




netradiationequivalentevaporation_netradiationequivalentevaporation = Factory(name='NetRadiationEquivalentEvaporation',
                authors='OpenAlea Consortium (wralea authors)',
                description=' It is given by dividing net radiation by latent heat of vaporization of water ',
                category='Unclassified',
                nodemodule='netradiationequivalentevaporation',
                nodeclass='netradiationequivalentevaporation',
                inputs=[{'interface': IFloat(min=0, max=10, step=1.000000), 'name': 'lambdaV', 'value': 2.454}, {'interface': IFloat(min=0, max=5000, step=1.000000), 'name': 'netRadiation', 'value': 1.566}],
                outputs=[{'interface': IFloat(min=0, max=5000, step=1.000000), 'name': 'netRadiationEquivalentEvaporation'}],
                widgetmodule=None,
                widgetclass=None,
               )




